import React from "react";
import { render, screen } from "@testing-library/react";
import App from "../pages";
import getMetaDescription from "../utils/getMetaDescription";
const userStory = `
Given no inital state,
When user navigates to the web page,
Then user sees the static information
`;
describe(userStory, () => {
  beforeEach(() => {
    render(<App />);
  })
  it("shows the phrase Next.js!", () => {
    const linkElement = screen.getByText(/Next.js!/i);
    expect(linkElement).toBeInTheDocument();
  });
  it("shows the correct headers", () => {
    const metaCollection = document.getElementsByTagName("meta");
    const descriptionMeta = getMetaDescription(0, (metaCollection as unknown) as HTMLMetaElement[]);
    expect(descriptionMeta).toEqual("Generated by create next app");
  });
});
